Location.create([
  { city: "Austin", state: "TX", country: "United States", slug: "austin" },
  { city: "Boston", state: "MA", country: "United States", slug: "boston" },
  { city: "Chicago", state: "IL", country: "United States", slug: "chicago" },
  { city: "New York", state: "NY", country: "United States", slug: "new-york" },
  { city: "Palo Alto", state: "CA", country: "United States", slug: "palo-alto" },
  { city: "Philadelphia", state: "PA", country: "United States", slug: "philadelphia" },
  { city: "Portland", state: "OR", country: "United States", slug: "portland" },
  { city: "Redwood City", state: "CA", country: "United States", slug: "redwood-city" },
  { city: "San Francisco", state: "CA", country: "United States", slug: "san-francisco" },
  { city: "San Jose", state: "CA", country: "United States", slug: "san-jose" },
  { city: "Seattle", state: "WA", country: "United States", slug: "seattle" },
  { city: "Washington, DC", country: "United States", slug: "washington-dc" },
  { city: "Amsterdam", country: "Netherlands", slug: "amsterdam" },
  { city: "Berlin", country: "Germany", slug: "berlin" },
  { city: "Dublin", country: "Ireland", slug: "dublin" },
  { city: "London", country: "United Kingdom", slug: "london" },
  { city: "Melbourne", country: "Australia", slug: "melbourne" },
  { city: "Shanghai", country: "China", slug: "shanghai" },
  { city: "Sydney", country: "Australia", slug: "sydney" },
  { city: "Tokyo", country: "Japan", slug: "tokyo" },
  { city: "Toronto", country: "Canada", slug: "toronto" },
  { city: "Vancouver", country: "Canada", slug: "vancouver" },
  { slug: "remote" }
])